namespace Bloomtown.Shared.Protocol;

public enum PacketType : byte
{
    PlayerInput = 1,
    EntityDelta = 2,
    ConnectAccept = 3,
    NpcInteractionRequest = 4,
    NpcInteractionResponse = 5,
    EconomyRequest = 6,
    EconomyResponse = 7,
    GatheringRequest = 8,
    GatheringResponse = 9,
    ClientQueryRequest = 10,
    ClientQueryResponse = 11,
    ChestRequest = 12,
    ChestResponse = 13,
    CommunityProjectRequest = 14,
    CommunityProjectResponse = 15,
    MilestoneRequest = 16,
    MilestoneResponse = 17,
    MilestoneNotification = 18,
    ProjectProposalRequest = 19,
    ProjectProposalResponse = 20,
    ProjectProposalNotification = 21,
    VillagePositionRequest = 22,
    VillagePositionResponse = 23,
    VillagePositionNotification = 24,
    HomeRequest = 25,
    HomeResponse = 26,
    CraftingRequest = 27,
    CraftingResponse = 28,
    GiftRequest = 29,
    GiftResponse = 30,
    NpcAmbientComment = 31,
    VillageAreaRequest = 32,
    VillageAreaResponse = 33,
    VillageAreaNotification = 34,
    PersonalRoutineRequest = 35,
    PersonalRoutineResponse = 36,
    CommunityActivityRequest = 37,
    CommunityActivityResponse = 38,
    LegacyFocusRequest = 39,
    LegacyFocusResponse = 40,
    EmotionalBondRequest = 41,
    EmotionalBondResponse = 42,
    DailyVillageActivityRequest = 43,
    DailyVillageActivityResponse = 44,
    DailyRhythmRequest = 45,
    DailyRhythmResponse = 46,
}